### ISSUE TITLE
Question: Dataset

### ISSUE THREAD

**Issue by daehoumich** [agrimgupta92/sgan#16]
Hi, Agrim

I am trying to make my own dataset following the same format that you used (i.e., eth, zara, hotel, and univ).

The data files have four columns though, I couldn't clearly understand what the value of each column represents.

If you may, could you explain it?

**Comment by angeliand** [comment]
Hi daehoumich,
Although I'm not Agrim, I hope my answer will be fit for your liking. 

If you check out the [sgan.data.trajectories.py](https://github.com/agrimgupta92/sgan/blob/master/sgan/data/trajectories.py) file, and inside that the [TrajectoryDataset](https://github.com/agrimgupta92/sgan/blob/master/sgan/data/trajectories.py#L71) class, you will find the answer. 
```
- data_dir: Directory containing dataset files in the format
        <frame_id> <ped_id> <x> <y>
```
Just to make things a bit clearer: 
* Every pedestrian has a unique ID (ped_id - second column), so that we can follow their movements/trajectories across different frames. 
* Frames also have an ID (frame_id - first column), because we need to know the correct order of them. 
* And finally, to know the position of a pedestrian x-y coordinates are given in the third and fourth column respectively.

**Comment by daehoumich** [comment]
Thank you so much~!

**Comment by mikegillimage** [comment]
Hi, this may sound silly, but does anyone know what is physical scale of the images in eth, zara and hotel datasets? Is there a way to get it from the homography matrix?

**Comment by amiryanj** [comment]
> Hi, this may sound silly, but does anyone know what is physical scale of the images in eth, zara and hotel datasets? Is there a way to get it from the homography matrix?

I am just telling you the basic things. Having Homography matrix and a pixel coordinate [u,v], you should  calculate H * [u, v, 1]^t => (x, y, z) and divide the resultant vector by (z) and you have the world coordinate: (x', y', 1). To know the boundaries of those scenes, it's enough to test the boundaries of the images; e.g. [0,0], [640, 480] for ETH!

**Comment by mikegillimage** [comment]
Thanks Amiryanj
